apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: ghcr.io/{YOUR_GITHUB_USERNAME}/checkout:latest
